# Generated by Django 5.2 on 2025-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0002_remove_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
