"""
Django settings for firm project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-c2*j9l*#lxi&3$j!!9*dq)r3#e#2u%8dbg_350_^0l@dv^+%4-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "assist.apps.AssistConfig",
    "django_daraja",
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "firm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "assist.context_processors.unread_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "firm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

import os

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # only if you have a 'static' folder in BASE_DIR
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # where collected files go

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email settings for Gmail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "Scheptoo376@gmail.com"  # <-- your Gmail address
EMAIL_HOST_PASSWORD = "pmia bhve hcfa baly"  # <-- your Gmail App Password
DEFAULT_FROM_EMAIL = "Scheptoo376@gmail.com"  # <-- same Gmail address (or a custom name like "Your Site <yourgmail@gmail.com>")

# Login URL for redirection (if user is not authenticated)
LOGIN_URL = "/login/"  # <-- use relative path unless you really want a full domain URL


LOGIN_REDIRECT_URL = "/"  # Where to redirect after login
LOGOUT_REDIRECT_URL = "/accounts/login/"  # Where to redirect after logout
LOGIN_URL = "/accounts/login/"  # This is the URL where users will go to log in


MPESA_ENVIRONMENT = "sandbox"

MPESA_CONSUMER_KEY = "WHBx5igrXKq4jQhooZgg4YJkzGxn87ZUMr63teJ9oPS0h0Ay"
MPESA_CONSUMER_SECRET = (
    "t6FiOuoXYDkaj6GmKJN14WiJW3aJBaG3H2iBSvKHQIqArqgAQL9v22C0JAsIAyLw"
)

MPESA_SHORT_CODE = "174379"
MPESA_EXPRESS_SHORTCODE = "174379"

MPESA_SHORTCODE_TYPE = "till_number"

MPESA_PASSKEY = "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"

MPESA_INITIATOR_USERNAME = "testapi"

MPESA_INITIATOR_SECURITY_CREDENTIALS = "Safaricom999!*!"

MPESA_CALLBACK_URL = "https://2d68-41-204-187-5.ngrok-free.app"
